version: "3.9"

services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "if [ ! -d node_modules ]; then npm install; fi && npm run start:dev"